import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SidebarMenu from '../components/SidebarMenu/SidebarMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cuentas claras',
  description: 'Generated by siendomiguel dev'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className} >
        <SidebarMenu />
        {children}
      </body>
    </html>
  )
}
